GET https://api.github.com

###

POST http://localhost:3001/notes
Content-Type: application/json

{
    "content": "hello api",
    "id": 8,
    "important": false
}

###
DELETE http://localhost:3001/notes/8

###
GET https://api.openweathermap.org/data/2.5/weather?lat=8.4963657&lon=4.5480484&appid=e859ca9b8b5c3b50c8aa6e821caf7725
###
GET http://api.openweathermap.org/geo/1.0/direct?q=Ilorin&appid=e859ca9b8b5c3b50c8aa6e821caf7725